Remove plone.app.referenceablebehavior in plone 5
4teamwork/ftw.iframeblock pull request #32
Opened 2020-05-27 16:37 UTC by busykoala

2020-05-28 12:10 UTC, Nachtalb requested changes

2020-05-28 12:10 UTC, Nachtalb commented on ftw/iframeblock/upgrades/20200527192955_remove_plone_app_referenceablebehavior/types/ftw.iframeblock.IFrameBlock.xml
> +    <property name="behaviors" purge=False>
Missing quotes
```suggestion
    <property name="behaviors" purge="False">
```

2020-05-28 14:34 UTC, busykoala commented on ftw/iframeblock/upgrades/20200527192955_remove_plone_app_referenceablebehavior/types/ftw.iframeblock.IFrameBlock.xml
> +    <property name="behaviors" purge=False>
Good catch!

2020-05-29 08:11 UTC, djowett-ftw approved these changes
LGTM

2020-05-29 08:12 UTC, merged